# Generated by Django 3.1.4 on 2020-12-07 13:35

from django.db import migrations, models
import django.utils.timezone
import eres.models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=eres.models.user_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(help_text='포스팅을 올린 사람 (user.username)', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(help_text='포스팅의 카테고리', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(help_text='포스팅의 내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성된 시간 (title)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='포스팅의 제목', max_length=200),
        ),
    ]
